name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Build and publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run rollup

      - name: Inject release version
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          sed -i "s/0\.0\.0-dev/${VERSION}/g" dist/Home-Assistant-Mail-And-Packages-Custom-Card.js

      - name: Upload JS to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Home-Assistant-Mail-And-Packages-Custom-Card.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
